all:
	make -C m19-core/
	make -C m19-app/

clean:
	make clean -C m19-core/
	make clean -C m19-app/


#export CLASSPATH=./m19-core/m19-core.jar:./m19-app/m19-app.jar:./po-uuilib/po-uuilib.jar

#export CVS_RSH=ssh
#export CVSROOT=:ext:ist192494@sigma.ist.utl.pt:/afs/ist.utl.pt/groups/leic-po/po19/cvs/080